version: "3.8"

services:
  gate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-gate
    restart: always
    ports:
      - 14281:14281
    command: "-h 0.0.0.0 -auth auth:50051"
    depends_on:
      - auth
      - kafka

  auth:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-auth
    restart: always
    command: "-h 0.0.0.0 -db-user auth_user -db-pass auth_pwd -db-addr mariadb:3306 -db-name auth_db"
    depends_on:
      - mariadb

  handler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-handler
    restart: always
    command: "-db-user log_user -db-pass log_pwd -db-addr clickhouse:8123 -db-name log_db -rabbitmq-user task -rabbitmq-pass task_pwd"
    depends_on:
      - kafka
      - clickhouse
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-worker
    restart: always
    command: "-rabbitmq-user task -rabbitmq-pass task_pwd"
    depends_on:
      - rabbitmq

  mariadb:
    image: mariadb:11
    restart: always
    command: "--init-file /init.sql"
    environment:
      MARIADB_ROOT_PASSWORD: 12345
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./deployments/maria-db-dev-init.sql:/init.sql"
    ports:
      - 13306:3306

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - "zookeeper-secrets:/etc/zookeeper/secrets"
      - "zookeeper-data:/var/lib/zookeeper/data"
      - "zookeeper-log:/var/lib/zookeeper/log"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    volumes:
      - "kafka-secrets:/etc/kafka/secrets"
      - "kafka-data:/var/lib/kafka/data"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:22.2
    restart: always
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: 123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: default
      CLICKHOUSE_UID: 0
      CLICKHOUSE_GID: 0
    volumes:
      - "clickhouse-log:/var/log/clickhouse-server"
      - "clickhouse-data:/var/lib/clickhouse"
      - "./deployments/clickhouse-db-dev-init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 18123:8123

  rabbitmq:
    image: rabbitmq:3.12
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: task
      RABBITMQ_DEFAULT_PASS: task_pwd
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

volumes:
  mariadb:
  kafka-secrets:
  kafka-data:
  zookeeper-secrets:
  zookeeper-data:
  zookeeper-log:
  clickhouse-data:
  clickhouse-log:
  rabbitmq-data:
